"""add image to announcement model

Revision ID: 14be6bc18c6f
Revises: a9d612551753
Create Date: 2024-01-09 20:23:00.123304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14be6bc18c6f'
down_revision = 'a9d612551753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImageUrl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ImageId', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.drop_column('ImageId')
        batch_op.drop_column('ImageUrl')

    # ### end Alembic commands ###
