"""change attendance foreign key from beneficiary to user

Revision ID: 16397713ccc0
Revises: 42c02738426e
Create Date: 2023-12-26 23:43:02.239487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16397713ccc0'
down_revision = '42c02738426e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserId', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('Attendance_BeneficiaryId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['UserId'], ['UserId'])
        batch_op.drop_column('BeneficiaryId')
        batch_op.drop_column('HasAttended')

    with op.batch_alter_table('Registration', schema=None) as batch_op:
        batch_op.alter_column('IsAssigned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Registration', schema=None) as batch_op:
        batch_op.alter_column('IsAssigned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('HasAttended', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('BeneficiaryId', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Attendance_BeneficiaryId_fkey', 'Beneficiary', ['BeneficiaryId'], ['BeneficiaryId'])
        batch_op.drop_column('UserId')

    # ### end Alembic commands ###
