"""remove proposed amount in budget table

Revision ID: 1c82776731a9
Revises: ff90e5db2ddd
Create Date: 2023-12-24 14:56:10.626439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c82776731a9'
down_revision = 'ff90e5db2ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_column('ProposedAmount')
        batch_op.drop_column('ApprovedAmount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ApprovedAmount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProposedAmount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('Amount')

    # ### end Alembic commands ###
