"""add unique constraint in attendance model

Revision ID: 1f1cf69e79a1
Revises: 16397713ccc0
Create Date: 2023-12-27 00:35:59.687302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1cf69e79a1'
down_revision = '16397713ccc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_activity', ['UserId', 'ActivityId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_activity', type_='unique')

    # ### end Alembic commands ###
