"""refactor project team attribute in project model

Revision ID: 32a9f7ba39db
Revises: 7f070f520cb3
Create Date: 2023-11-30 14:34:59.434752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a9f7ba39db'
down_revision = '7f070f520cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.alter_column('ProjectTeam',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.alter_column('ProjectTeam',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
