"""add IsAssigned attribute to registration for assigning students to take attendace and to take evaluation for beneficiaries

Revision ID: 42c02738426e
Revises: 1c82776731a9
Create Date: 2023-12-24 21:40:19.477409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c02738426e'
down_revision = '1c82776731a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsAssigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Registration', schema=None) as batch_op:
        batch_op.drop_column('IsAssigned')

    # ### end Alembic commands ###
