"""add attributes to activity model

Revision ID: 50be9b609a44
Revises: 8ead7147c883
Create Date: 2023-11-26 17:59:36.474829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50be9b609a44'
down_revision = '8ead7147c883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartTime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('EndTime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('Location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_column('Location')
        batch_op.drop_column('EndTime')
        batch_op.drop_column('StartTime')

    # ### end Alembic commands ###
