"""Add budget and item

Revision ID: 51dc0e11397f
Revises: 32a9f7ba39db
Create Date: 2023-12-22 09:08:39.415600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dc0e11397f'
down_revision = '32a9f7ba39db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Budget',
    sa.Column('BudgetId', sa.Integer(), nullable=False),
    sa.Column('FundType', sa.String(length=20), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('ProposedAmount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ApprovedAmount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ProjectId', sa.Integer(), nullable=False),
    sa.Column('CollaboratorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CollaboratorId'], ['Collaborator.CollaboratorId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ProjectId'], ['Project.ProjectId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('BudgetId')
    )
    op.create_table('Item',
    sa.Column('ItemId', sa.Integer(), nullable=False),
    sa.Column('ItemName', sa.String(length=50), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('IsPurchased', sa.Boolean(), nullable=False),
    sa.Column('DatePurchased', sa.DateTime(), nullable=True),
    sa.Column('ReceiptUrl', sa.Text(), nullable=True),
    sa.Column('ReceiptId', sa.Text(), nullable=True),
    sa.Column('ActivityId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ActivityId'], ['Activity.ActivityId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ItemId')
    )
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('ApprovedBudget')
        batch_op.drop_column('ProposedBudget')
        batch_op.drop_column('FundType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FundType', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProposedBudget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ApprovedBudget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))

    op.drop_table('Item')
    op.drop_table('Budget')
    # ### end Alembic commands ###
