"""fix column and relationship same name in question and evaluation models

Revision ID: 6ef682e257a4
Revises: 0605d4a58378
Create Date: 2023-12-30 23:58:05.345345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef682e257a4'
down_revision = '0605d4a58378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatorId', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['CreatorId'], ['UserId'], ondelete='CASCADE')

    with op.batch_alter_table('Question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatorId', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['CreatorId'], ['UserId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CreatorId')

    with op.batch_alter_table('Evaluation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CreatorId')

    # ### end Alembic commands ###
