"""update user attributes

Revision ID: a9d612551753
Revises: 6fb4005e6b9d
Create Date: 2024-01-09 02:48:55.483905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d612551753'
down_revision = '6fb4005e6b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserNumber', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('DateOfBirth', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('PlaceOfBirth', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ResidentialAddress', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('MobileNumber', sa.String(length=11), nullable=False))
        batch_op.alter_column('Email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_User_UserNumber'), ['UserNumber'], unique=True)
        batch_op.drop_column('Birthdate')
        batch_op.drop_column('Address')
        batch_op.drop_column('ContactDetails')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ContactDetails', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Birthdate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_User_UserNumber'))
        batch_op.alter_column('Email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('MobileNumber')
        batch_op.drop_column('ResidentialAddress')
        batch_op.drop_column('PlaceOfBirth')
        batch_op.drop_column('DateOfBirth')
        batch_op.drop_column('UserNumber')

    # ### end Alembic commands ###
