"""create location table

Revision ID: ec50bea773c5
Revises: 6ef682e257a4
Create Date: 2024-01-02 22:30:09.191450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50bea773c5'
down_revision = '6ef682e257a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('LocationId', sa.Integer(), nullable=False),
    sa.Column('LocationName', sa.String(length=55), nullable=False),
    sa.Column('Longitude', sa.String(length=55), nullable=False),
    sa.Column('Latitude', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('LocationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Location')
    # ### end Alembic commands ###
