"""adjusted models

Revision ID: f3afe38ce134
Revises: ebaed73ce61b
Create Date: 2023-11-21 01:37:47.514182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3afe38ce134'
down_revision = 'ebaed73ce61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Speaker', sa.Text(), nullable=False))
        batch_op.drop_constraint('Activity_SpeakerId_fkey', type_='foreignkey')
        batch_op.drop_column('SpeakerId')
        batch_op.drop_column('EndTime')
        batch_op.drop_column('StartTime')

    with op.batch_alter_table('Collaborator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SignedMOAUrl', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('SignedMOAFileId', sa.Text(), nullable=False))
        batch_op.drop_column('KeyPersonnel')

    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Rationale', sa.Text(), nullable=False))
        batch_op.drop_constraint('ExtensionProgram_CollaboratorId_fkey', type_='foreignkey')
        batch_op.drop_column('Status')
        batch_op.drop_column('ProposedBudget')
        batch_op.drop_column('ApprovedBudget')
        batch_op.drop_column('FundType')
        batch_op.drop_column('DateApproved')
        batch_op.drop_column('CollaboratorId')
        batch_op.drop_column('ImplementationDate')

    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('Implementer', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('CollaboratorId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ProjectTeam', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('TargetGroup', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('EndDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ProposedBudget', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('ApprovedBudget', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('FundType', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ImpactStatement', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ProjectProposalUrl', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ProjectProposalFileId', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'Collaborator', ['CollaboratorId'], ['CollaboratorId'], ondelete='CASCADE')
        batch_op.drop_column('Rationale')
        batch_op.drop_column('Name')
        batch_op.drop_column('ProjectScope')
        batch_op.drop_column('BeneficiariesClassifications')
        batch_op.drop_column('NumberOfBeneficiaries')

    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.drop_constraint('Response_SurveyId_fkey', type_='foreignkey')
        batch_op.drop_column('SurveyId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SurveyId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Response_SurveyId_fkey', 'Survey', ['SurveyId'], ['SurveyId'], ondelete='CASCADE')

    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NumberOfBeneficiaries', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('BeneficiariesClassifications', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProjectScope', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Rationale', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ProjectProposalFileId')
        batch_op.drop_column('ProjectProposalUrl')
        batch_op.drop_column('ImpactStatement')
        batch_op.drop_column('FundType')
        batch_op.drop_column('ApprovedBudget')
        batch_op.drop_column('ProposedBudget')
        batch_op.drop_column('EndDate')
        batch_op.drop_column('TargetGroup')
        batch_op.drop_column('ProjectTeam')
        batch_op.drop_column('CollaboratorId')
        batch_op.drop_column('Implementer')
        batch_op.drop_column('Title')

    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImplementationDate', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CollaboratorId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('DateApproved', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('FundType', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ApprovedBudget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProposedBudget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ExtensionProgram_CollaboratorId_fkey', 'Collaborator', ['CollaboratorId'], ['CollaboratorId'], ondelete='CASCADE')
        batch_op.drop_column('Rationale')

    with op.batch_alter_table('Collaborator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('KeyPersonnel', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('SignedMOAFileId')
        batch_op.drop_column('SignedMOAUrl')

    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartTime', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('EndTime', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('SpeakerId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Activity_SpeakerId_fkey', 'Speaker', ['SpeakerId'], ['SpeakerId'], ondelete='CASCADE')
        batch_op.drop_column('Speaker')

    # ### end Alembic commands ###
