"""remove description in budget table

Revision ID: ff90e5db2ddd
Revises: 51dc0e11397f
Create Date: 2023-12-22 11:42:10.807025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff90e5db2ddd'
down_revision = '51dc0e11397f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.drop_column('Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
